/*
   -- Piddle --

   To compile this code using RemoteXY library 4.1.8 or later version
   download by link http://remotexy.com/en/library/
   To connect using RemoteXY mobile app by link http://remotexy.com/en/download/
     - for ANDROID 4.18.03 or later version;
     - for iOS 1.14.1 or later version;

   To interact with the GUI, please refer to the manual:
   https://remotexy.com/ru/help/code/interaction/

   This source code was automatically generated by the RemoteXY editor and
   is an example for the RemoteXY library.
   Licensed under the MIT License. See the LICENSE file in the RemoteXY library
   root (https://github.com/RemoteXY/RemoteXY-Arduino-library) for full license
   details.
*/

//////////////////////////////////////////////
//        RemoteXY include library          //
//////////////////////////////////////////////

// you can enable debug logging to Serial at 115200
//#define REMOTEXY__DEBUGLOG

// RemoteXY select connection mode and include library
#define REMOTEXY_MODE__ESP32CORE_BLE

#include <BLEDevice.h>

// RemoteXY connection settings
#define REMOTEXY_BLUETOOTH_NAME "Phonic Bloom"


#include <RemoteXY.h>
#include <RH_ASK.h>
#include <SPI.h> // Not actually used but needed to compile

#include "../radio.hpp"
#include "../constants.hpp"

// RemoteXY GUI configuration
#pragma pack(push, 1)
uint8_t const PROGMEM RemoteXY_CONF_PROGMEM[] =   // 514 bytes V19
  { 255,23,0,0,0,251,1,19,0,0,0,0,24,1,126,200,2,1,0,15,
  0,129,32,18,62,12,64,17,66,114,105,103,104,116,110,101,115,115,0,129,
  33,47,60,12,64,17,83,101,110,115,105,116,105,118,105,116,121,0,4,12,
  33,104,10,128,2,26,4,12,60,104,10,128,2,26,129,43,76,35,12,64,
  17,83,112,101,101,100,0,4,12,89,104,10,128,2,26,2,71,161,30,12,
  1,2,26,31,31,79,78,0,79,70,70,0,129,21,162,48,12,64,17,82,
  97,105,110,98,111,119,0,2,75,180,30,12,1,2,26,31,31,79,78,0,
  79,70,70,0,129,16,181,57,12,64,17,78,111,114,109,97,108,105,122,101,
  0,129,25,103,79,12,64,17,80,97,116,116,101,114,110,32,108,101,110,103,
  116,104,0,4,12,117,104,10,128,2,26,129,32,129,57,12,64,17,84,105,
  108,101,32,111,102,102,115,101,116,0,4,12,143,104,10,128,2,26,131,97,
  5,22,12,1,151,148,31,0,6,17,0,2,11,35,24,11,0,2,26,31,
  31,79,78,0,79,70,70,0,2,11,51,24,11,0,2,26,31,31,79,78,
  0,79,70,70,0,2,11,67,24,11,0,2,26,31,31,79,78,0,79,70,
  70,0,2,11,83,24,11,0,2,26,31,31,79,78,0,79,70,70,0,2,
  11,99,24,11,0,2,26,31,31,79,78,0,79,70,70,0,2,11,115,24,
  11,0,2,26,31,31,79,78,0,79,70,70,0,2,11,131,24,11,0,2,
  26,31,31,79,78,0,79,70,70,0,2,11,147,24,11,0,2,26,31,31,
  79,78,0,79,70,70,0,2,11,163,24,11,0,2,26,31,31,79,78,0,
  79,70,70,0,2,51,35,24,11,0,2,26,31,31,79,78,0,79,70,70,
  0,2,51,51,24,11,0,2,26,31,31,79,78,0,79,70,70,0,2,51,
  67,24,11,0,2,26,31,31,79,78,0,79,70,70,0,2,51,83,24,11,
  0,2,26,31,31,79,78,0,79,70,70,0,2,51,99,24,11,0,2,26,
  31,31,79,78,0,79,70,70,0,2,51,115,24,11,0,2,26,31,31,79,
  78,0,79,70,70,0,131,97,5,22,12,1,151,148,31,0,9,10,62,141,
  24,24,48,4,26,31,79,78,0,31,79,70,70,0 };

// this structure defines all the variables and events of your control interface
struct RemoteXY_t {

    // input variables
  int8_t brightnessSlider; // from 0 to 100
  int8_t sensitivitySlider; // from 0 to 100
  int8_t speedSlider; // from 0 to 100
  uint8_t rainbowSwitch; // =1 if switch ON and =0 if OFF, from 0 to 1
  uint8_t normalizeBandsSwitch; // =1 if switch ON and =0 if OFF, from 0 to 1
  int8_t patternLengthSlider; // from 0 to 100
  int8_t tileOffsetSlider; // from 0 to 100
  uint8_t rgb01Switch; // =1 if switch ON and =0 if OFF, from 0 to 1
  uint8_t rgb02Switch; // =1 if switch ON and =0 if OFF, from 0 to 1
  uint8_t rgb03Switch; // =1 if switch ON and =0 if OFF, from 0 to 1
  uint8_t rgb04Switch; // =1 if switch ON and =0 if OFF, from 0 to 1
  uint8_t rgb05Switch; // =1 if switch ON and =0 if OFF, from 0 to 1
  uint8_t rgb06Switch; // =1 if switch ON and =0 if OFF, from 0 to 1
  uint8_t rgb07Switch; // =1 if switch ON and =0 if OFF, from 0 to 1
  uint8_t rgb08Switch; // =1 if switch ON and =0 if OFF, from 0 to 1
  uint8_t rgb09Switch; // =1 if switch ON and =0 if OFF, from 0 to 1
  uint8_t rgb10Switch; // =1 if switch ON and =0 if OFF, from 0 to 1
  uint8_t rgb11Switch; // =1 if switch ON and =0 if OFF, from 0 to 1
  uint8_t rgb12Switch; // =1 if switch ON and =0 if OFF, from 0 to 1
  uint8_t rgb13Switch; // =1 if switch ON and =0 if OFF, from 0 to 1
  uint8_t rgb14Switch; // =1 if switch ON and =0 if OFF, from 0 to 1
  uint8_t rgb15Switch; // =1 if switch ON and =0 if OFF, from 0 to 1
  uint8_t rgbButton; // =1 if state is ON, else =0, from 0 to 1

    // other variable
  uint8_t connect_flag;  // =1 if wire connected, else =0

} RemoteXY;
#pragma pack(pop)

inline bool operator==(const RemoteXY_t& a, const RemoteXY_t& b) {
  return memcmp(&a, &b, sizeof(RemoteXY_t)) == 0;
}
inline bool operator!=(const RemoteXY_t& a, const RemoteXY_t& b) {
  return !(a == b);
}

/////////////////////////////////////////////
//           END RemoteXY include          //
/////////////////////////////////////////////
// RH_ASK(uint16_t speed=2000, uint8_t rxPin=11, uint8_t txPin=12, uint8_t pttPin=10, bool pttInverted=false)
RH_ASK driver(2000, RH_INVALID_PIN, 23, RH_INVALID_PIN);

void setup() {
  RemoteXY_Init();
  Serial.begin(115200);
  if (!driver.init()) {
    while (true) {
      Serial.println("Radio init failed");
      delay(1000);
    }
  }
  RemoteXY.brightnessSlider = DEFAULT_BRIGHTNESS;
  RemoteXY.rainbowSwitch = false;
  RemoteXY.normalizeBandsSwitch = true;
  RemoteXY.speedSlider = DEFAULT_SPEED;
  RemoteXY.sensitivitySlider = DEFAULT_SENSITIVITY;
  RemoteXY.patternLengthSlider = DEFAULT_PATTERN_LENGTH;
  RemoteXY.tileOffsetSlider = DEFAULT_TILE_OFFSET;
}

void sendRadioUpdate();

void loop() {
  RemoteXY_t previous(RemoteXY);
  while (true) {
    RemoteXY_Handler();

    if (RemoteXY.connect_flag) {
      previous.connect_flag = RemoteXY.connect_flag;
      if (previous != RemoteXY) {
        Serial.printf("%ld sending\n", millis());
        sendRadioUpdate();
      }
      previous = RemoteXY;
    }
  }
}

void sendRadioUpdate() {
  RadioConfigMessage_t message;
  message.brightness = RemoteXY.brightnessSlider;
  message.sensitivity = RemoteXY.sensitivitySlider;
  message.speed = RemoteXY.speedSlider;
  message.patternLength = RemoteXY.patternLengthSlider;
  message.tileOffset = RemoteXY.tileOffsetSlider;
  message.rainbow = RemoteXY.rainbowSwitch;
  message.normalizeBands = RemoteXY.normalizeBandsSwitch;
  message.rgbButton = RemoteXY.rgbButton;
  uint16_t mask = 0;
  for (int i = 0; i < 15; ++i) {
    mask |= static_cast<uint16_t>((&RemoteXY.rgb01Switch)[i]) << i;
  }
  message.rgb = mask;
  uint8_t buffer[sizeof(message)];
  memcpy(buffer, &message, sizeof(message));
  driver.send(buffer, sizeof(message));
  driver.waitPacketSent();
}
